DROP DATABASE IF EXISTS linkgraph CASCADE;
CREATE DATABASE IF NOT EXISTS linkgraph;
SET DATABASE = linkgraph;

DROP TABLE IF EXISTS links;
CREATE TABLE IF NOT EXISTS links (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	url STRING UNIQUE,
	retrieved_at TIMESTAMP
);

DROP TABLE IF EXISTS edges;
CREATE TABLE IF NOT EXISTS edges (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	src UUID NOT NULL REFERENCES links(id) ON DELETE CASCADE,
	dst UUID NOT NULL REFERENCES links(id) ON DELETE CASCADE,
	updated_at TIMESTAMP,
	CONSTRAINT edge_links UNIQUE(src,dst)
);
